# Note: builds at
# https://readthedocs.com/projects/tiledb-inc-tiledb-singlecell/builds/
# (permissioned)

# Don't build any extra formats
formats: []

# Use RTD config version 2
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: doc/source/conf.py

# python:
#   version: 3.8
#   install:
#     # this order is important: we need to get cmake
#     - requirements: doc/requirements_doc.txt
#     - method: setuptools
#       path: .

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    # `pip install -e .` or `python setup.py develop` will _not_ let python find the tiledbsc package
    # within sphinx build
    #- apt-get install python3-sphinx
    - pip install -r doc/requirements_doc.txt
    - cd apis/python && pip install . && cd ../..
    - sphinx-build -E -T -b html -d _readthedocs/doctrees -D language=en doc/source _readthedocs/html
