name: TileDB-SOMA C++ formatting

on:
  pull_request:
    paths-ignore:
      - 'apis/r/**'
      - 'apis/python/**'
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check C++ Format  
        run: |  
          ./scripts/run-clang-format.sh . clang-format 0 \  
          $(find libtiledbsoma -name "*.cc" -or -name "*.h")    
